services:
  portfolio:
    build: .
    container_name: portfolio_web
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`raulbm.numinformatica.com`)"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls.certresolver=myresolver"
      - "traefik.http.services.portfolio.loadbalancer.server.port=80"

networks:
  traefik:
    external: true
    name: traefik
